version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "${PRISMA_SERVER_PORT}:${PRISMA_SERVER_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_SERVER_PORT}
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
